KEYWORDS = {
    # 🧠 Artificial Intelligence / ML / Data
    "ai": "Artificial Intelligence",
    "artificial intelligence": "Artificial Intelligence",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "neural network": "Neural Networks",
    "transformer": "AI Transformers",
    "llm": "Large Language Models",
    "openai": "OpenAI",
    "chatgpt": "ChatGPT",
    "anthropic": "Anthropic",
    "gemini": "Gemini (Google AI)",
    "mistral": "Mistral AI",
    "hugging face": "Hugging Face",
    "diffusion": "Generative Models",

    # 📦 Software Architecture & Engineering
    "microservices": "Microservices",
    "architecture": "Software Architecture",
    "distributed systems": "Distributed Systems",
    "design patterns": "Design Patterns",
    "event-driven": "Event-Driven Architecture",
    "serverless": "Serverless",
    "monolith": "Monolithic Architecture",
    "domain driven": "Domain-Driven Design",
    "ddd": "Domain-Driven Design",
    "hexagonal": "Hexagonal Architecture",
    "clean architecture": "Clean Architecture",
    "event sourcing": "Event Sourcing",
    "cqrs": "CQRS",

    # 💻 Programming Languages / Paradigms
    "kotlin": "Kotlin",
    "java": "Java",
    "python": "Python",
    "go": "Go",
    "rust": "Rust",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "functional programming": "Functional Programming",
    "oop": "Object-Oriented Programming",

    # ☁️ Cloud, DevOps, Infra
    "devops": "DevOps",
    "cloud": "Cloud Computing",
    "aws": "Amazon Web Services",
    "gcp": "Google Cloud",
    "azure": "Microsoft Azure",
    "terraform": "Terraform",
    "kubernetes": "Kubernetes",
    "docker": "Docker",
    "containers": "Containers",
    "ci/cd": "CI/CD",
    "github actions": "GitHub Actions",

    # 🧰 Tools, Platforms & Ecosystem
    "github": "GitHub",
    "gitlab": "GitLab",
    "redis": "Redis",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "graphql": "GraphQL",
    "rest api": "REST API",
    "grpc": "gRPC",
    "api gateway": "API Gateway",
    "message queue": "Messaging/Queues",
    "kafka": "Apache Kafka",
    "rabbitmq": "RabbitMQ",

    # 🔐 Security
    "security": "Security",
    "authentication": "Authentication",
    "authorization": "Authorization",
    "oauth": "OAuth",
    "jwt": "JWT",
    "encryption": "Encryption",

    # 🌍 General IT / Tech Trends
    "software engineering": "Software Engineering",
    "information technology": "Information Technology",
    "tech stack": "Tech Stack",
    "digital transformation": "Digital Transformation",
    "scalability": "Scalability",
    "performance": "Performance",
    "observability": "Observability",
    "monitoring": "Monitoring",
    "logging": "Logging"
}