KEYWORDS = {
    # 🧠 Artificial Intelligence / ML
    "ai": "Artificial Intelligence",
    "artificial intelligence": "Artificial Intelligence",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "neural network": "Neural Networks",
    "transformer": "AI Transformers",
    "llm": "Large Language Models",
    "large language model": "Large Language Models",
    "openai": "OpenAI",
    "chatgpt": "ChatGPT",
    "anthropic": "Anthropic",
    "gemini": "Gemini (Google AI)",
    "mistral": "Mistral AI",
    "llama": "LLaMA",
    "hugging face": "Hugging Face",
    "diffusion": "Generative Models",
    "stable diffusion": "Stable Diffusion",
    "computer vision": "Computer Vision",
    "nlp": "Natural Language Processing",
    "rag": "RAG",
    "fine-tuning": "Fine-Tuning",
    "fine tuning": "Fine-Tuning",
    "embedding": "Embeddings",
    "vector database": "Vector Databases",
    "multimodal": "Multimodal AI",
    "alignment": "AI Alignment",
    "hallucination": "AI Hallucination",
    "prompt engineering": "Prompt Engineering",
    "context window": "Context Window",
    "inference": "AI Inference",
    "quantization": "Model Quantization",
    "ai agent": "AI Agents",
    "agentic": "AI Agents",

    # 📦 Software Architecture & Engineering
    "microservices": "Microservices",
    "architecture": "Software Architecture",
    "distributed systems": "Distributed Systems",
    "design patterns": "Design Patterns",
    "event-driven": "Event-Driven Architecture",
    "serverless": "Serverless",
    "domain driven": "Domain-Driven Design",
    "ddd": "Domain-Driven Design",
    "event sourcing": "Event Sourcing",
    "cqrs": "CQRS",

    # 💻 Programming Languages / Paradigms
    "kotlin": "Kotlin",
    "python": "Python",
    "go": "Go",
    "rust": "Rust",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "functional programming": "Functional Programming",

    # ☁️ Cloud, DevOps, Infra
    "devops": "DevOps",
    "kubernetes": "Kubernetes",
    "docker": "Docker",
    "terraform": "Terraform",
    "ci/cd": "CI/CD",
    "github actions": "GitHub Actions",
    "mlops": "MLOps",

    # 🧰 Data & Platforms
    "redis": "Redis",
    "postgres": "PostgreSQL",
    "graphql": "GraphQL",
    "kafka": "Apache Kafka",
    "grpc": "gRPC",

    # 🔐 Security
    "security": "Security",
    "cybersecurity": "Cybersecurity",
    "vulnerability": "Vulnerability",
    "cve": "CVE",
    "zero-day": "Zero-Day",
    "zero day": "Zero-Day",
    "exploit": "Exploit",
    "malware": "Malware",
    "ransomware": "Ransomware",
    "phishing": "Phishing",
    "encryption": "Encryption",
    "cryptography": "Cryptography",
    "authentication": "Authentication",
    "oauth": "OAuth",
    "zero trust": "Zero Trust",
    "mfa": "Multi-Factor Authentication",
    "threat intelligence": "Threat Intelligence",
    "apt": "Advanced Persistent Threat",
    "red team": "Red Team",
    "bug bounty": "Bug Bounty",
    "pen test": "Penetration Testing",
    "penetration testing": "Penetration Testing",
    "incident response": "Incident Response",
    "data breach": "Data Breach",
    "supply chain attack": "Supply Chain Attack",
    "siem": "SIEM",
    "backdoor": "Backdoor",

    # 🌍 Scalability / Observability
    "scalability": "Scalability",
    "observability": "Observability",
    "monitoring": "Monitoring",
}
