name: Create Pull request
on:
  push:
    branches:
      - learning
jobs:
  createPRFromLearning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update content
          title: Update content
          body: Update content
          branch: main
