name: Auto Create Pull Request

on:
  push:
    branches:
      - learn

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensures the repo is checked out

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get latest commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Create Pull Request
        run: gh pr create -B main -H learn --title "${{ env.commit_message }}" --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
