name: Auto Create Pull Request

on:
  push:
    branches:
      - learn

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          base: learning
          title: "Auto PR from learning to main"
          body: "This is an automated PR generated on every push to the learning branch."
          labels: "automated-pr"
          draft: true  # If you want the PR to be created as a draft, set this to true
